# Generated by Django 3.2.5 on 2025-01-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('number', models.CharField(max_length=15, unique=True, verbose_name='学号')),
                ('role', models.CharField(choices=[('1', '学生'), ('2', '教师'), ('3', '教务员')], default=1, max_length=1, verbose_name='角色')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='居住地址')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='超级用户')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理员')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户表',
            },
        ),
    ]
