# Generated by Django 3.2.5 on 2025-01-01 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='课程名称')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='课程简介')),
                ('enable', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '课程一览',
                'verbose_name_plural': '课程一览',
            },
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='成绩')),
                ('course', models.ForeignKey(limit_choices_to={'enable': True}, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='课程')),
                ('student', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生成绩表',
                'verbose_name_plural': '学生成绩表',
            },
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(limit_choices_to={'enable': True}, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='课程')),
                ('teacher', models.ManyToManyField(limit_choices_to={'role': 2}, to=settings.AUTH_USER_MODEL, verbose_name='任课教师')),
            ],
            options={
                'verbose_name': '教师任课表',
                'verbose_name_plural': '教师任课表',
            },
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(limit_choices_to={'enable': True}, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='课程')),
                ('student', models.ManyToManyField(limit_choices_to={'role': 1}, related_name='course', to=settings.AUTH_USER_MODEL, verbose_name='选课学生')),
            ],
            options={
                'verbose_name': '学生选课信息表',
                'verbose_name_plural': '学生选课信息表',
            },
        ),
    ]
